services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: miaupassword
      MYSQL_DATABASE: mimiau
    ports:
      - "3306:3306"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.v/init.sql

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - DB-HOST=db
    depends_on:
      - db
