# --- MIDDLEWARE FOR FRONTEND ---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: spa-redirect
  namespace: default
spec:
  errors:
    status:
      - "404"
    query: /
    service:
      name: angular-service
      port: 80
---
# --- FRONTEND SERVICE ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-game
  template:
    metadata:
      labels:
        app: angular-game
    spec:
      containers:
        - name: frontend
          image: docker.io/library/mimiau-frontend:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: angular-service
spec:
  ports:
    - port: 80
  selector:
    app: angular-game
---
# --- PHP BACKEND SERVICE ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-api
  template:
    metadata:
      labels:
        app: php-api
    spec:
      containers:
        - name: php
          image: docker.io/library/mimiau-backend-php:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: php-service
spec:
  ports:
    - port: 80
      targetPort: 9000
  selector:
    app: php-api
---
# --- NATIVE TRAEFIK INGRESSROUTE ---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: mimiau-ingressroute
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/api`)
      kind: Rule
      services:
        - name: php-service
          port: 80
    - match: PathPrefix(`/`)
      kind: Rule
      middlewares:
        - name: spa-redirect
      services:
        - name: angular-service
          port: 80
